# Schema para o sistema de estoque EstocAí

type Usuario @table {
  id: String! @default(expr: "auth.uid")
  nome: String!
  email: String!
  senha: String!
}

type Produto @table {
  id: String! @default(expr: "uuidV4()")
  codigo: String!
  nome: String!
  descricao: String!
  categoria: String!
  precoVenda: Float!
  precoCusto: Float!
  estoqueAtual: Int!
  estoqueMinimo: Int!
  fornecedor: String
  observacoes: String
  dataCriacao: Timestamp! @default(expr: "request.time")
  dataAtualizacao: Timestamp! @default(expr: "request.time")
  ativo: Boolean! @default(expr: "true")
  usuarioId: String!
}

type ItemCompra @table {
  id: String! @default(expr: "uuidV4()")
  produtoId: String!
  quantidade: Int!
  custoNoMomento: Float!
  subtotal: Float!
  compraId: String!
}

type Compra @table {
  id: String! @default(expr: "uuidV4()")
  valorTotal: Float!
  fornecedor: String!
  numeroNota: String
  data: Timestamp! @default(expr: "request.time")
  observacoes: String
  status: String!
  usuarioId: String!
}

type ItemVenda @table {
  id: String! @default(expr: "uuidV4()")
  produtoId: String!
  quantidade: Int!
  precoNoMomento: Float!
  subtotal: Float!
  vendaId: String!
}

type Venda @table {
  id: String! @default(expr: "uuidV4()")
  valorTotal: Float!
  plataforma: String!
  formaPagamento: String!
  data: Timestamp! @default(expr: "request.time")
  nomeCliente: String
  contatoCliente: String
  observacoes: String
  status: String!
  usuarioId: String!
}
